#!/bin/sh -x

# C2 build script which runs as "root" on first boot
#
# NOTE: variables that start with a percent-sign will be substituted
# using /var/cache/c2/build-inputs.json.
#
# Use double-percent to escape percent signs.

# install packages
apt-get install -yq --force-yes curl openssl postgresql ruby1.9.1 ruby1.9.1-dev build-essential libsqlite3-ruby1.9.1 libsqlite3-dev libpq-dev

# download/install user-specified packages
apt-get install -y --force-yes %(additional_packages)s

# create/install application database
psql postgres -c "CREATE ROLE ubuntu WITH CREATEDB LOGIN PASSWORD '%(database_password)s'"

# force utf-8
sudo dpkg-reconfigure locales
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# install bundler and a few other gems
sudo gem install bundler rails sinatra therubyracer
sudo chown -R ubuntu.ubuntu /home/ubuntu/.gem

# bootstrap rails
cd /home/ubuntu/repo
bundle install
rake db:create

# create start script for upstart
mkdir -p /home/ubuntu/bin
cat > /home/ubuntu/bin/start-rails <<EOF
#!/bin/sh
cd ~/repo
rails server
EOF
chmod +x /home/ubuntu/bin/start-rails
chown -R ubuntu.ubuntu /home/ubuntu/bin

# install upstart daemon
cat > /etc/init/rails.conf <<EOF
#!upstart
description "rails dev server"
author      "OpDemand"

start on (local-filesystems and net-device-up IFACE=eth0)
stop on shutdown

script
   export HOME="/home/ubuntu"
   exec sudo -u ubuntu -i "/home/ubuntu/bin/start-rails" 2>&1 >> /var/log/rails.log
end script
EOF

# start the daemon
start rails
